//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkEnums
{
    using System;
    
    public enum Color : int
    {
        Black = 0,
        Red = 1,
        Silver = 2
    }
}
